src: Support strikethrough faces
mawww/kakoune pull request #3862
Opened 2020-11-02 20:08 UTC by eraserhd

2020-11-03 02:49 UTC, lenormf commented
Do you have a usecase for this? Markup?

2020-11-04 18:22 UTC, eraserhd commented
This came up working on kak-jira.  JIRA has markup for added and removed text.  These are rendered on the web as underline and strikethrough.

That being said, IMHO text rendering in Kakoune doesn’t need to match anything else — this seemed like it could be generally useful.

2020-11-10 20:42 UTC, mawww requested changes

2020-11-10 20:42 UTC, mawww commented on src/face.hh
> +    Strikethrough = 1 << 10,
I'd rather have all non-final attributes together, so could you move it next to italic, as `1 << 7`

2020-11-10 20:42 UTC, mawww commented on src/terminal_ui.cc
> -    static constexpr int attr_table[]{ 0, 4, 7, 5, 1, 2, 3 };
while the new code is a bit more explicit, I kind of like the simplicity of having a onliner table, which should be possible again if you change Strikethrough as requested above.

2020-11-10 20:42 UTC, mawww commented on src/terminal_ui.cc
> +        for (int i = 0; i < sizeof(attr_table) / sizeof(attr_table[0]); ++i)
we could use `std::size(attr_table)` here to avoid having to do the division dance.

2020-11-11 15:25 UTC, eraserhd commented
@mawww All requested changes made.

(I also tried to make the attribute bit numbers equal to the terminal codes, which required skipping a few, but it ended up not being an improvement.)

2020-11-17 09:13 UTC, mawww commented
cherry-picked

2020-11-17 09:13 UTC, closed without merging