Performance improvements for update-option and set-option
mawww/kakoune pull request #4092
Opened 2021-03-08 22:17 UTC by eraserhd

Closes #4084

The use of `std::inplace_merge()` improves the performance of `set-option -add` much more than expected, given that it is theoretically linear, so I suspect the actual implementation binary searches for the insertion place, or checks if the lists are already sorted, or something?

Before this, `set-option` grew to 341548 us per invocation.  After, it stayed under 4000 us per invocation.

Not happy with the abstractions or the duplication of the comparator from the option_list_postprocess(), but I already spent a day on this instead of my Real Job. :D  Perhaps we need some kind of OptionTraits<>?  Let me know and I'll fix.

2021-03-08 23:06 UTC, mawww requested changes

2021-03-08 23:06 UTC, mawww commented on src/option_types.cc
> +    opt.insert(opt.end(),
This returns an iterator to the first inserted element, so no need for original_size

2021-03-08 23:06 UTC, mawww commented on src/option_types.hh
> +bool option_add_from_strings(Vector<RangeAndString, MemoryDomain::Options>& opt, ConstArrayView<String> strs);
I think this should be in highlighters.hh next to the other RangeAndString methods.

2021-03-08 23:06 UTC, mawww commented on src/option_types.cc
> +bool option_add_from_strings(Vector<RangeAndString, MemoryDomain::Options>& opt, ConstArrayView<String> strs)
This should be in highlighters.cc

2021-03-08 23:06 UTC, mawww commented on src/option_types.cc
> +    return not vec.empty();
Maybe early-out on vec.empty() ?

2021-03-09 16:29 UTC, eraserhd commented
This should be good.  A sample file went from 12m27s to 1m3s with non-debug build.

Notes:
* The first display update takes about 5 seconds.  I haven't looked into that.
* The most significant time per iteration now is `execute-keys '<a-:><a-;>Gh'`, used to ensure each iteration processes any partial escape sequences from the last iteration.... Although this probably doesn't actually work, and it would be a good idea to track partial state in an option anyway.

2021-03-10 05:53 UTC, lenormf commented
Will this help with the performance issues in #3438 ?

2021-03-10 21:04 UTC, merged